name: Continues Evaluation Notte

on:
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: '0 */4 * * *' # 9:00 AM IST
  workflow_dispatch:
    inputs:
      pipeline_id:
        description: 'Pipeline ID'
        required: true
        default: '75'
      user_id:
        description: 'User ID'
        required: true
        default: ''
      model:
        description: 'Model'
        required: true
        type: choice
        options:
          - gpt-4o
          - gemini-2.5-pro-preview-06-05
          - claude-sonnet-4-20250514
        default: 'gemini-2.5-pro-preview-06-05'
      advanced_settings:
        description: 'Advanced Settings (JSON)'
        required: false
        default: '{"episodes" : 1}'
      episodes:
        description: 'Number of episodes to run'
        required: true
        type: number
        default: 1

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA
        id: short-sha
        run: echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
        
      - name: Send payload to Paradigm Shift
        run: |
          cat > payload.json <<'JSON'
          {
            "agent_name": "Notte",
            "branch": "${{ github.ref_name }}",
            "commit": "${{ github.sha }}",
            "commit_sha": "${{ steps.short-sha.outputs.short_sha }}",
            "pipeline_id": "${{ inputs.pipeline_id || '75' }}",
            "user_id": "${{ inputs.user_id || '' }}",
            "model": "${{ inputs.model || 'gemini-2.5-pro-preview-06-05' }}",
            "advanced_settings": ${{ toJSON(inputs.advanced_settings || '{"episodes" : 1}') }},
            "episodes": ${{ inputs.episodes || 1 }}
          }
          JSON
          curl -fsS -H "Content-Type: application/json" -d @payload.json https://paradigm-shift.ai/api/pre-ce
